#pragma once

#include "hal/gpio_types.h"

/* -----------------------------------------------------------------------
 * ECU hardware and simulator configuration.
 * Update these definitions to match your board layout and test needs.
 * ----------------------------------------------------------------------- */

/* CAN (TWAI) pins */
// #define ECU_CAN_TX_PIN GPIO_NUM_4
// #define ECU_CAN_RX_PIN GPIO_NUM_5
#define ECU_CAN_TX_PIN GPIO_NUM_1  // s3
#define ECU_CAN_RX_PIN GPIO_NUM_21 // s3

/* CAN simulator timing */
#define ECU_CAN_BITRATE 500000
#define ECU_CAN_MESSAGES_PER_SEC 10

/* CAN frame generated by the simulator */
#define ECU_CAN_ID 0x201U
#define ECU_CAN_DLC 8U
#define ECU_CAN_DATA_BYTES {0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08}
